name: Push Swagger to SwaggerHub

on:
  push:
    branches:
      - MWPAP-15992-enable-swagger-git-integration
      - platform-workflow  # Change this to your desired branch
#    paths:
#      - "sample-git-rnd/bpm-service_rnd/swagger.yaml"

jobs:
  push-to-swaggerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js (if needed for SwaggerHub CLI)
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # You can use your preferred version

      - name: Install SwaggerHub CLI
        run: |
          npm install -g swaggerhub-cli

      - name: Push Swagger file to SwaggerHub
        env:
          SWAGGERHUB_API_KEY: "655c3450-fa4c-4bfc-b193-cfdc55d84692"
          #${{ secrets.SWAGGERHUB_API_KEY }}
        run: |
          # Replace these with your SwaggerHub owner, API name, and version
          # swaggerhub api:update AdvancedComputerSoft/platform-flow/0.0.1 --file bpm-service/swagger.yaml
          echo "Changes push to swaggerhub:::::::::::"
